# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/linuxstorage/git/batchMaliciousRAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/linuxstorage/git/batchMaliciousRAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/linuxstorage/git/batchMaliciousRAM/CMakeFiles /media/linuxstorage/git/batchMaliciousRAM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/linuxstorage/git/batchMaliciousRAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ram_frontend.exe

# Build rule for target.
ram_frontend.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ram_frontend.exe
.PHONY : ram_frontend.exe

# fast build rule for target.
ram_frontend.exe/fast:
	$(MAKE) -f CMakeFiles/ram_frontend.exe.dir/build.make CMakeFiles/ram_frontend.exe.dir/build
.PHONY : ram_frontend.exe/fast

#=============================================================================
# Target rules for targets named SPLIT_COMMIT

# Build rule for target.
SPLIT_COMMIT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SPLIT_COMMIT
.PHONY : SPLIT_COMMIT

# fast build rule for target.
SPLIT_COMMIT/fast:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/build
.PHONY : SPLIT_COMMIT/fast

#=============================================================================
# Target rules for targets named BYTEARRAYVEC

# Build rule for target.
BYTEARRAYVEC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BYTEARRAYVEC
.PHONY : BYTEARRAYVEC

# fast build rule for target.
BYTEARRAYVEC/fast:
	$(MAKE) -f CMakeFiles/BYTEARRAYVEC.dir/build.make CMakeFiles/BYTEARRAYVEC.dir/build
.PHONY : BYTEARRAYVEC/fast

#=============================================================================
# Target rules for targets named commit_test_snd

# Build rule for target.
commit_test_snd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commit_test_snd
.PHONY : commit_test_snd

# fast build rule for target.
commit_test_snd/fast:
	$(MAKE) -f CMakeFiles/commit_test_snd.dir/build.make CMakeFiles/commit_test_snd.dir/build
.PHONY : commit_test_snd/fast

#=============================================================================
# Target rules for targets named commit_test_rcv

# Build rule for target.
commit_test_rcv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commit_test_rcv
.PHONY : commit_test_rcv

# fast build rule for target.
commit_test_rcv/fast:
	$(MAKE) -f CMakeFiles/commit_test_rcv.dir/build.make CMakeFiles/commit_test_rcv.dir/build
.PHONY : commit_test_rcv/fast

#=============================================================================
# Target rules for targets named libBDX

# Build rule for target.
libBDX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libBDX
.PHONY : libBDX

# fast build rule for target.
libBDX/fast:
	$(MAKE) -f libBDX/CMakeFiles/libBDX.dir/build.make libBDX/CMakeFiles/libBDX.dir/build
.PHONY : libBDX/fast

#=============================================================================
# Target rules for targets named libRAM

# Build rule for target.
libRAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libRAM
.PHONY : libRAM

# fast build rule for target.
libRAM/fast:
	$(MAKE) -f libRAM/CMakeFiles/libRAM.dir/build.make libRAM/CMakeFiles/libRAM.dir/build
.PHONY : libRAM/fast

commitTestReceiver.o: commitTestReceiver.cpp.o

.PHONY : commitTestReceiver.o

# target to build an object file
commitTestReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/commit_test_rcv.dir/build.make CMakeFiles/commit_test_rcv.dir/commitTestReceiver.cpp.o
.PHONY : commitTestReceiver.cpp.o

commitTestReceiver.i: commitTestReceiver.cpp.i

.PHONY : commitTestReceiver.i

# target to preprocess a source file
commitTestReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/commit_test_rcv.dir/build.make CMakeFiles/commit_test_rcv.dir/commitTestReceiver.cpp.i
.PHONY : commitTestReceiver.cpp.i

commitTestReceiver.s: commitTestReceiver.cpp.s

.PHONY : commitTestReceiver.s

# target to generate assembly for a file
commitTestReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/commit_test_rcv.dir/build.make CMakeFiles/commit_test_rcv.dir/commitTestReceiver.cpp.s
.PHONY : commitTestReceiver.cpp.s

commitTestSender.o: commitTestSender.cpp.o

.PHONY : commitTestSender.o

# target to build an object file
commitTestSender.cpp.o:
	$(MAKE) -f CMakeFiles/commit_test_snd.dir/build.make CMakeFiles/commit_test_snd.dir/commitTestSender.cpp.o
.PHONY : commitTestSender.cpp.o

commitTestSender.i: commitTestSender.cpp.i

.PHONY : commitTestSender.i

# target to preprocess a source file
commitTestSender.cpp.i:
	$(MAKE) -f CMakeFiles/commit_test_snd.dir/build.make CMakeFiles/commit_test_snd.dir/commitTestSender.cpp.i
.PHONY : commitTestSender.cpp.i

commitTestSender.s: commitTestSender.cpp.s

.PHONY : commitTestSender.s

# target to generate assembly for a file
commitTestSender.cpp.s:
	$(MAKE) -f CMakeFiles/commit_test_snd.dir/build.make CMakeFiles/commit_test_snd.dir/commitTestSender.cpp.s
.PHONY : commitTestSender.cpp.s

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.o: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.o

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.o

# target to build an object file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.o:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.o
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.o

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.i: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.i

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.i

# target to preprocess a source file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.i:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.i
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.i

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.s: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.s

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.s

# target to generate assembly for a file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.s:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.s
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.cpp.s

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.o: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.o

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.o

# target to build an object file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.o:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.o
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.o

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.i: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.i

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.i

# target to preprocess a source file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.i:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.i
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.i

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.s: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.s

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.s

# target to generate assembly for a file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.s:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.s
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.cpp.s

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.o: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.o

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.o

# target to build an object file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.o:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.o
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.o

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.i: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.i

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.i

# target to preprocess a source file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.i:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.i
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.i

media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.s: media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.s

.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.s

# target to generate assembly for a file
media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.s:
	$(MAKE) -f CMakeFiles/SPLIT_COMMIT.dir/build.make CMakeFiles/SPLIT_COMMIT.dir/media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.s
.PHONY : media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.cpp.s

media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.o: media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.o

.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.o

# target to build an object file
media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.o:
	$(MAKE) -f CMakeFiles/BYTEARRAYVEC.dir/build.make CMakeFiles/BYTEARRAYVEC.dir/media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.o
.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.o

media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.i: media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.i

.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.i

# target to preprocess a source file
media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.i:
	$(MAKE) -f CMakeFiles/BYTEARRAYVEC.dir/build.make CMakeFiles/BYTEARRAYVEC.dir/media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.i
.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.i

media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.s: media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.s

.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.s

# target to generate assembly for a file
media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.s:
	$(MAKE) -f CMakeFiles/BYTEARRAYVEC.dir/build.make CMakeFiles/BYTEARRAYVEC.dir/media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.s
.PHONY : media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.cpp.s

ramRunner/SimpleRunner.o: ramRunner/SimpleRunner.cpp.o

.PHONY : ramRunner/SimpleRunner.o

# target to build an object file
ramRunner/SimpleRunner.cpp.o:
	$(MAKE) -f CMakeFiles/ram_frontend.exe.dir/build.make CMakeFiles/ram_frontend.exe.dir/ramRunner/SimpleRunner.cpp.o
.PHONY : ramRunner/SimpleRunner.cpp.o

ramRunner/SimpleRunner.i: ramRunner/SimpleRunner.cpp.i

.PHONY : ramRunner/SimpleRunner.i

# target to preprocess a source file
ramRunner/SimpleRunner.cpp.i:
	$(MAKE) -f CMakeFiles/ram_frontend.exe.dir/build.make CMakeFiles/ram_frontend.exe.dir/ramRunner/SimpleRunner.cpp.i
.PHONY : ramRunner/SimpleRunner.cpp.i

ramRunner/SimpleRunner.s: ramRunner/SimpleRunner.cpp.s

.PHONY : ramRunner/SimpleRunner.s

# target to generate assembly for a file
ramRunner/SimpleRunner.cpp.s:
	$(MAKE) -f CMakeFiles/ram_frontend.exe.dir/build.make CMakeFiles/ram_frontend.exe.dir/ramRunner/SimpleRunner.cpp.s
.PHONY : ramRunner/SimpleRunner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... ram_frontend.exe"
	@echo "... SPLIT_COMMIT"
	@echo "... BYTEARRAYVEC"
	@echo "... commit_test_snd"
	@echo "... commit_test_rcv"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... libBDX"
	@echo "... libRAM"
	@echo "... commitTestReceiver.o"
	@echo "... commitTestReceiver.i"
	@echo "... commitTestReceiver.s"
	@echo "... commitTestSender.o"
	@echo "... commitTestSender.i"
	@echo "... commitTestSender.s"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.o"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.i"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-rec.s"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.o"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.i"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit-snd.s"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.o"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.i"
	@echo "... media/linuxstorage/git/SplitCommit/src/split-commit/split-commit.s"
	@echo "... media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.o"
	@echo "... media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.i"
	@echo "... media/linuxstorage/git/SplitCommit/src/util/byte-array-vec.s"
	@echo "... ramRunner/SimpleRunner.o"
	@echo "... ramRunner/SimpleRunner.i"
	@echo "... ramRunner/SimpleRunner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

